# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
- group: BST

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: '.npmrc'
    customEndpoint: 'kurlytail-npm'

- task: CmdLine@2
  inputs:
    script: |
      echo ${GitbubPAT}
      env

- task: CmdLine@2
  inputs:
    script: |
      cat .npmrc
      npm install
      npm run build
      npm run lint
      npm run test
      npm --no-git-tag-version version patch
      npm publish

- task: PublishTestResults@1
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'test-report.xml'

- task: CmdLine@2
  condition: succeeded()
  inputs:
    script: 'git push https://${GithubPAT}@github.com/kurlytail/gen-lib.git HEAD:master'


